export const ROUTE_PATHS = {
  HOME: '/',
  ABOUT: '/about',
  PRODUCTS: '/products',
  DOCS: '/docs',
  BIBLIO_RENAME: '/biblio-rename',
  BIBLIO_CLEAN: '/biblio-clean',
  BIBLIO_AUDIT: '/biblio-audit',
  BIBLIO_TABLE: '/biblio-table',
  AI_RENAME_VARIANTS: '/ai-rename-variants',
  UXBIBLIO: '/uxbiblio',
  ADMIN: '/admin',
  BLOG: '/blog',
  BLOG_ARTICLE: '/blog/:slug',
  RESOURCES: '/resources',
  REMOVE_PROTOTYPE_LINK: '/resources/remove-prototype-link',
} as const;
