export const ROUTE_PATHS = {
  HOME: '/',
  ABOUT: '/about',
  PRODUCTS: '/products',
  DOCS: '/docs',
  BIBLIO_RENAME: '/figma-component-variant-renamer',
  BIBLIO_CLEAN: '/figma-plugin-remove-prototype-links',
  BIBLIO_AUDIT: '/figma-design-system-audit-plugin',
  BIBLIO_TABLE: '/figma-table-builder',
  BIBLIO_STATES: '/figma-component-states',
  BIBLIO_ORGANIZE: '/figma-organize-design-files-plugin',
  AI_RENAME_VARIANTS: '/ai-rename-variants',
  UXBIBLIO: '/uxbiblio',
  ADMIN: '/admin',
  BLOG: '/blog',
  BLOG_ARTICLE: '/blog/:slug',
  RESOURCES: '/resources',
  REMOVE_PROTOTYPE_LINK: '/resources/remove-prototype-link',
  LEARN: '/learn',
  LEARN_DESIGN_OPS_FUNDAMENTALS: '/learn/design-ops-fundamentals',
  TUTORIALS: '/tutorials',
  SCALE_RESIZER: '/figma-marketing-resizer-plugin',
  // Programmatic SEO routes
  USE_CASES: '/use-cases',
  USE_CASE: '/use-cases/:slug',
  PERSONAS: '/for',
  PERSONA: '/for/:slug',
} as const;
