export const ROUTE_PATHS = {
  HOME: '/',
  ABOUT: '/about',
  PRODUCTS: '/products',
  DOCS: '/docs',
  BIBLIO_RENAME: '/biblio-rename',
  BIBLIO_CLEAN: '/figma-plugin-remove-prototype-links',
  BIBLIO_AUDIT: '/figma-design-system-audit-plugin',
  BIBLIO_TABLE: '/biblio-table',
  BIBLIO_ORGANIZE: '/figma-organize-design-files-plugin',
  AI_RENAME_VARIANTS: '/ai-rename-variants',
  UXBIBLIO: '/uxbiblio',
  ADMIN: '/admin',
  BLOG: '/blog',
  BLOG_ARTICLE: '/blog/:slug',
  RESOURCES: '/resources',
  REMOVE_PROTOTYPE_LINK: '/resources/remove-prototype-link',
  LEARN: '/learn',
  LEARN_DESIGN_OPS_FUNDAMENTALS: '/learn/design-ops-fundamentals',
} as const;
